version: "3.6"
services:
  bulletin-board:
    build: bulletin-board
    image: docker.io/bulletin-board
    ports:
    - ${bulletin-board.port}:8080
    secrets:
    - source: cosmos-connection
      target: /app/config/cosmosDbConfig.js
secrets:
  cosmos-connection:
    file: cosmos/cosmosDbConfig.js
